export const channels = {};

export const PREFERENCES_IDS = {
  OPEN_AT_LOGIN: 'OPEN_AT_LOGIN',
  SHORTCUT_TOGGLE_WINDOW: 'SHORTCUT_TOGGLE_WINDOW',
  SHORTCUT_TOGGLE_CLIPBOARD_HISTORY: 'SHORTCUT_TOGGLE_CLIPBOARD_HISTORY'
};
